#pragma once

#if defined(_KERNEL_MODE) || defined(KNHV_KERNEL_BUILD)
#include <ntddk.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#include "knhv_abi.h"
#include "knhv_nested.h"

#define KNHV_CONTROL_DEVICE_NAME L"\\Device\\KNHVControl"
#define KNHV_CONTROL_DOS_NAME L"\\DosDevices\\KNHVControl"
#define KNHV_NESTED_DEVICE_NAME L"\\Device\\KNHVNestedTest"
#define KNHV_NESTED_DOS_NAME L"\\DosDevices\\KNHVNestedTest"

#define IOCTL_KNHV_QUERY_CAPS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_KNHV_REGISTER_CLIENT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_KNHV_QUERY_SESSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_KNHV_NESTED_INSTRUCTION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, \
             FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_KNHV_REFLECT_EXIT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, \
             FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_KNHV_RELEASE_SESSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_KNHV_QUERY_CAPS_V2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_KNHV_ACQUIRE_LEASE_V2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_KNHV_RELEASE_LEASE_V2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_WRITE_DATA)
